### ISSUE TITLE
/usr/src/app/find_wave.py contains html

### ISSUE THREAD

**Issue by robmarkcole** [renemarc/balena-airthingswave#1]
Hi
as title and in image below

![image](https://user-images.githubusercontent.com/11855322/59928198-1d2acd80-9436-11e9-99c6-3e1d98f80a9c.png)

**Comment by renemarc** [comment]
Ack! Thanks for the heads-up, I'll fix that asap!

**Comment by renemarc** [comment]
Hi @robmarkcole,

Airthings have placed their website behind CloudFlare, which prevents downloading the `find_wave.py` file using the command-line. 😢I'm reaching out to @Airthings so that they can place this hard-to-get code file on their own GitHub account instead.

In the meantime, you can manually run these commands inside a Terminal window (SSH or balenaCloud) to fetch the `find_wave.py` file from their CDN:

```sh
rm /usr/src/app/find_wave.py
wget --directory-prefix=/usr/src/app/ https://cdn2.hubspot.net/hubfs/4406702/Tech/find_wave.py
```

**Comment by robmarkcole** [comment]
I wonder why they would do that.. Thanks for the instruction

**Comment by renemarc** [comment]
@allcontributors please add @robmarkcole for his bug report.

**Comment by renemarc** [comment]
The Dockerfiles were updated to point to www-prefixed URLs. This should fix this multiple-redirection issue until Airthings make their `find_wave.py` script available on GitHub. Thanks @robmarkcole! 😃
